name: Build and Push Comm Service to Google Artifact Registry

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GH_SA_KEY }}'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build --no-cache \
            --build-arg GH_PAT=${{ secrets.GH_PAT }} \
            -t asia-south1-docker.pkg.dev/dev-hivemindd/hivemindd-dev-repo/comm-service:${{ steps.vars.outputs.sha_short }} \
            .

      - name: Push Docker image
        run: |
          docker push asia-south1-docker.pkg.dev/dev-hivemindd/hivemindd-dev-repo/comm-service:${{ steps.vars.outputs.sha_short }}

      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: hivemindd/infrastructure.git
          token: ${{ secrets.GH_PAT }}
          ref: dev

      - name: Update image tag in manifest
        run: |
          yq e '.spec.template.spec.containers[0].image = "asia-south1-docker.pkg.dev/dev-hivemindd/hivemindd-dev-repo/comm-service:${{ steps.vars.outputs.sha_short }}"' -i local-dev/comm-service/helm/values.yaml
          yq e '.image.repository = "asia-south1-docker.pkg.dev/dev-hivemindd/hivemindd-dev-repo/comm-service"' -i local-dev/comm-service/helm/values.yaml
          yq e '.image.tag = "${{ steps.vars.outputs.sha_short }}"' -i local-dev/comm-service/helm/values.yaml

      - name: Commit and push to GitOps repo
        run: |
          cd local-dev/comm-service/helm
          git config user.name "HiveMindd CI Bot"
          git config user.email "sathisha.b@hivemindd.com"
          git add values.yaml
          git commit -m "Deploy comm-service:${{ steps.vars.outputs.sha_short }}"
          git push
